dist: trusty
language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - cppcheck
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- cppcheck --error-exitcode=1 *.c
- restructuredtext-lint --encoding=UTF-8 README
- make
- make install PREFIX=$HOME/.local
- netaway -h
- netaway wget https://www.example.org/; [ $? -eq 4 ]

# vim:ts=2 sts=2 sw=2 et
